"""empty message

Revision ID: 1b43633bef4d
Revises: 7c1a671523f7
Create Date: 2026-05-12 20:42:30.398168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b43633bef4d'
down_revision = '7c1a671523f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_column('datetime')

    # ### end Alembic commands ###
