"""empty message

Revision ID: 2e653c4e2f2e
Revises: 558f1553735c
Create Date: 2026-05-11 16:55:34.467992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e653c4e2f2e'
down_revision = '558f1553735c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_coords', sa.String(length=140), server_default='0.000000, 0.000000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('location_coords')

    # ### end Alembic commands ###
