"""empty message

Revision ID: 355dfce22751
Revises: 1e1a8852a301
Create Date: 2026-05-11 17:48:22.789026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355dfce22751'
down_revision = '1e1a8852a301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_video')
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), server_default='0.0', nullable=False))
        batch_op.add_column(sa.Column('lon', sa.Float(), server_default='0.0', nullable=False))
        batch_op.drop_column('location_coords')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_coords', sa.VARCHAR(length=140), server_default=sa.text("'0.000000, 0.000000'"), nullable=False))
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    op.create_table('_alembic_tmp_video',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lon', sa.FLOAT(), nullable=False),
    sa.Column('filepath', sa.VARCHAR(length=140), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
