"""empty message

Revision ID: 401be1a282c6
Revises: e6bae11a4a98
Create Date: 2026-05-18 08:03:09.089294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401be1a282c6'
down_revision = 'e6bae11a4a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comment_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comment_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_path'))
        batch_op.drop_column('parent_id')
        batch_op.drop_column('path')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
