"""empty message

Revision ID: 4f8de39b20f5
Revises: 50f7bfd60e3b
Create Date: 2026-05-14 07:22:33.129412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8de39b20f5'
down_revision = '50f7bfd60e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=48), server_default='', nullable=False))

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=48), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
