"""empty message

Revision ID: 50f7bfd60e3b
Revises: b1fdaae01f21
Create Date: 2026-05-13 18:56:38.700387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f7bfd60e3b'
down_revision = 'b1fdaae01f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_level', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.drop_column('ip_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_country', sa.VARCHAR(), server_default=sa.text("('')"), nullable=True))

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('privacy_level')

    # ### end Alembic commands ###
