"""empty message

Revision ID: 511c18cd5cca
Revises: 4126e49f6548
Create Date: 2026-05-11 16:51:19.472788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511c18cd5cca'
down_revision = '4126e49f6548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_coords', sa.String(length=140), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('location_coords')

    # ### end Alembic commands ###
