"""empty message

Revision ID: 62afa12f7882
Revises: e6d255d1b8e3
Create Date: 2026-05-12 18:28:50.395623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62afa12f7882'
down_revision = 'e6d255d1b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('liker_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
