"""empty message

Revision ID: 85b6f38e36b4
Revises: 4f8de39b20f5
Create Date: 2026-05-14 16:42:21.847724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b6f38e36b4'
down_revision = '4f8de39b20f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'video', ['video_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
