"""empty message

Revision ID: e6d255d1b8e3
Revises: f7f54c3fe074
Create Date: 2026-05-12 06:26:10.532415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d255d1b8e3'
down_revision = 'f7f54c3fe074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), server_default='', nullable=False))
        batch_op.add_column(sa.Column('hashtags', sa.String(length=500), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('hashtags')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
