"""empty message

Revision ID: f31935c7954e
Revises: ad8052213026
Create Date: 2026-05-18 08:14:52.085383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31935c7954e'
down_revision = 'ad8052213026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_comment_video_id'), ['video_id'], unique=False)
        batch_op.create_foreign_key(None, 'video', ['video_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comment_video_id'))
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
