"""empty message

Revision ID: f7f54c3fe074
Revises: 355dfce22751
Create Date: 2026-05-12 06:25:22.264195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f54c3fe074'
down_revision = '355dfce22751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('hashtags', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('hashtags')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
